http:
  port: 8080
  middlewares:
    - name: cors
    - name: logging
  endpoints:
    - targets:
        - uri: http://127.0.0.1:8000
          weight: 100
          color: test-service
        - uri: http://127.0.0.1:8001
          weight: 300
        - uri: http://127.0.0.1:8002
          weight: 600
      protocol: http
      timeout: 2000
      loadBalance: rotation
      predicates:
        path: test-service/*/{id}
        method: GET
      middlewares:
        - name: strip_prefix
          args:
            call: 1
    - targets:
        - uri: http://127.0.0.1:8003
          weight: 100
      protocol: grpc
      timeout: 2000
      predicates:
        path: /hello.Greater/*
        method: POST
      middlewares:
        - name: grpc
          args:
            httpStatus: 400
            grpcErrorTemplate: '{"code": {status},"message": "{message}"}'